mrbs:
    image: cartertsai/debain-ssh
    ports:
        - "2222:22"
        - "8080:80"
    links: 
        - db
    
db:
    image: cartertsai/debain-ssh        
    ports:
        - "2200:22"
        - "8880:80"
        