---
- hosts: mrbs
  gather_facts: no
  become: True
  become_method: sudo
  become_user: root

  tasks:
    - name: install lib
      apt: name={{item}} state=installed
      with_items:
        - php5
- hosts: postgre
  gather_facts: no
  become: True
  become_user: postgres

  vars:
    dbname: test
    dbuser: admin
    dbpassword: testtest

  tasks:
    - name: install postgresql
      apt: name={{item}}
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
    - name: ensure database is created
      postgresql_db: name={{dbname}}
                       encoding='UTF8'
                       lc_collate='en_US.UTF-8'
                       lc_ctype='en_US.UTF-8'


    - name: create database user
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL
