---
- hosts: mrbs
  gather_facts: no
  become: True
  become_method: sudo
  become_user: root
  vars:
    tmp_dir: /tmp
    mrbs_file_link: "http://netix.dl.sourceforge.net/project/mrbs/mrbs/MRBS%201.5.0/mrbs-1.5.0.tar.gz"
    mrbs_dir_name: "{{tmp_dir}}/mrbs-1.5.0"

  tasks:
    - name: install lib
      apt: name={{item}} state=installed
      with_items:
        - php5

    - name: create directory
      file: path={{tmp_dir}}/mrbs state=directory

    - name: unarchive mrbs
      unarchive: src={{mrbs_file_link}} dest={{tmp_dir}}/mrbs copy=no

    - name: Show mrbs
      shell: ls -al {{tmp_dir}}/mrbs
      ignore_errors: yes

- hosts: postgre
  gather_facts: no
  become: True
  become_method: sudo
  become_user: root

  vars:
    dbname: mrbs
    dbuser: mrbsuser
    dbpassword: testtest

  tasks:
    - name: install postgresql
      apt: name={{item}} update_cache=yes cache_valid_time=3600
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
    - name: create postgre group
      group: name=postgres state=present

    - name: create postgre user
      user: name=postgres group="postgres" state=present

    - name: ensure database is created
      become: True
      become_user: postgres
      become_method: sudo
      postgresql_db: name={{dbname}}
                       encoding='UTF8'
                       lc_collate='en_US.UTF-8'
                       lc_ctype='en_US.UTF-8'

    - name: create database user
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

    - name: ensure user does not have unnecessary privilege
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
