---
- hosts: mrbs
  gather_facts: no
  become: True
  become_method: sudo
  become_user: root
  vars:
    tmp_dir: /tmp
    mrbs_file_link: "http://netix.dl.sourceforge.net/project/mrbs/mrbs/MRBS%201.5.0/mrbs-1.5.0.tar.gz"
    mrbs_dir_name: "{{tmp_dir}}/mrbs-1.5.0"

  tasks:
    - name: install lib
      apt: name={{item}} state=installed
      with_items:
        - php5
    - name: download mrbs
      get_url: url={{mrbs_file_link}} dest={{tmp_dir}}

    - name: unarchive mrbs
      unarchive: src={{tmp_dir}}/mrbs-1.5.0.tar.gz

- hosts: postgre
  gather_facts: no
  become: True
  become_user: postgres

  vars:
    dbname: mrbs
    dbuser: mrbsuser
    dbpassword: testtest

  tasks:
    - name: install postgresql
      apt: name={{item}}
      with_items:
        - postgresql
        - libpq-dev
        - python-psycopg2
    - name: ensure database is created
      postgresql_db: name={{dbname}}
                       encoding='UTF8'
                       lc_collate='en_US.UTF-8'
                       lc_ctype='en_US.UTF-8'

    - name: create database user
      postgresql_user: db={{dbname}} name={{dbuser}} password={{dbpassword}} priv=ALL

    - name: ensure user does not have unnecessary privilege
      postgresql_user: name={{dbuser}} role_attr_flags=NOSUPERUSER,NOCREATEDB
